trigger: none

pool:
  name: 'Default'
  demands:
  - agent.name -equals intnoondaidoa01

resources:
  repositories:
  - repository: templates
    type: git
    name: IntelOneAPIApollo/pipelines
    ref: main

stages:
- stage: Build
  displayName: Build - Scanning Source Code
  jobs:
  - template: PipelineTemplates/build-template.yml@templates