services:
  intelligent-indexing:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - PORT=${PORT:-8888}
      - WORKSPACE=/workspace
      - DATA_DIR=/workspace/data
      - OUTPUT_DIR=/workspace/output
    image: ${COMPOSE_PROJECT_NAME}:latest
    stdin_open: true 
    tty: true
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "${WORKSPACE}:/workspace"
      - "${DATA_DIR}:/workspace/data"
      - "${OUTPUT_DIR}:/workspace/output"
    command: bash -c "source /opt/conda/bin/activate && conda activate jupyter_server && jupyter notebook --notebook-dir=/workspace --ip 0.0.0.0 --port ${PORT} --no-browser --allow-root"
